// <auto-generated />
namespace Price_Configurator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Refactorpricequote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Refactorpricequote));
        
        string IMigrationMetadata.Id
        {
            get { return "201701130228348_Refactor price quote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
